name: tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >= 3.8
  - biobb_pytorch
  - ipywidgets == 7.7.2 # Required for nglview in Google Colab
  - jupyter
  - numpy
  - mdtraj
  - nglview
  - requests